<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generated="20191221 14:47:19.902" generator="Robot 3.1.2 (Python 2.7.10 on darwin)">
<suite source="/Users/vinoshantharmalenkam/Desktop/CSCC01-Fall-2019/a2/rootFolder/testCases" id="s1" name="testCases">
<suite source="/Users/vinoshantharmalenkam/Desktop/CSCC01-Fall-2019/a2/rootFolder/testCases/Test1PUT.robot" id="s1-s1" name="Test1PUT">
<test id="s1-s1-t1" name="TestPost200">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:20.047" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:20.048" starttime="20191221 14:47:20.047"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:20.049" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:20.049" starttime="20191221 14:47:20.048"></status>
</kw>
<kw name="Create List" library="BuiltIn">
<doc>Returns a list containing given items.</doc>
<arguments>
<arg>a2</arg>
<arg>test</arg>
</arguments>
<assign>
<var>${list}</var>
</assign>
<msg timestamp="20191221 14:47:20.049" level="INFO">${list} = [u'a2', u'test']</msg>
<status status="PASS" endtime="20191221 14:47:20.049" starttime="20191221 14:47:20.049"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone</arg>
<arg>author=Jake Peralta</arg>
<arg>content=some content</arg>
<arg>tags=${list}</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:20.050" level="INFO">${params} = {u'title': u'Emma Stone', u'author': u'Jake Peralta', u'content': u'some content', u'tags': [u'a2', u'test']}</msg>
<status status="PASS" endtime="20191221 14:47:20.050" starttime="20191221 14:47:20.049"></status>
</kw>
<kw name="Put Request" library="RequestsLibrary">
<doc>Send a PUT request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:20.052" level="INFO">PUT Request using : uri=/api/v1/post, files=None, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"title": "Emma Stone", "author": "Jake Peralta", "content": "some content", "tags": ["a2", "test"]} 
json=None</msg>
<msg timestamp="20191221 14:47:20.061" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10458af50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.264" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459e790&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.668" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459e3d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.673" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459ee90&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:20.674" starttime="20191221 14:47:20.050"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:20.674" critical="yes" starttime="20191221 14:47:20.046">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459ee90&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s1-t2" name="TestPost400">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:20.676" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:20.677" starttime="20191221 14:47:20.676"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:20.678" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:20.678" starttime="20191221 14:47:20.678"></status>
</kw>
<kw name="Create List" library="BuiltIn">
<doc>Returns a list containing given items.</doc>
<arguments>
<arg>a2</arg>
<arg>test</arg>
</arguments>
<assign>
<var>${list}</var>
</assign>
<msg timestamp="20191221 14:47:20.679" level="INFO">${list} = [u'a2', u'test']</msg>
<status status="PASS" endtime="20191221 14:47:20.679" starttime="20191221 14:47:20.679"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone</arg>
<arg>content=some content</arg>
<arg>tags=${list}</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:20.680" level="INFO">${params} = {u'title': u'Emma Stone', u'content': u'some content', u'tags': [u'a2', u'test']}</msg>
<status status="PASS" endtime="20191221 14:47:20.680" starttime="20191221 14:47:20.680"></status>
</kw>
<kw name="Put Request" library="RequestsLibrary">
<doc>Send a PUT request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:20.682" level="INFO">PUT Request using : uri=/api/v1/post, files=None, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"title": "Emma Stone", "content": "some content", "tags": ["a2", "test"]} 
json=None</msg>
<msg timestamp="20191221 14:47:20.685" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046144d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.891" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104614690&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.296" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104614850&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.301" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046149d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:21.301" starttime="20191221 14:47:20.681"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:21.302" critical="yes" starttime="20191221 14:47:20.675">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046149d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" endtime="20191221 14:47:21.303" starttime="20191221 14:47:19.928"></status>
</suite>
<suite source="/Users/vinoshantharmalenkam/Desktop/CSCC01-Fall-2019/a2/rootFolder/testCases/Test2GET.robot" id="s1-s2" name="Test2GET">
<test id="s1-s2-t1" name="TestPost200Title">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:21.311" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:21.311" starttime="20191221 14:47:21.310"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:21.312" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:21.312" starttime="20191221 14:47:21.312"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:21.313" level="INFO">${params} = {u'title': u'Emma Stone'}</msg>
<status status="PASS" endtime="20191221 14:47:21.313" starttime="20191221 14:47:21.312"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>json=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:21.314" level="INFO">GET Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data=None 
json={u'title': u'Emma Stone'}</msg>
<msg timestamp="20191221 14:47:21.316" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625490&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.518" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.926" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.931" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625990&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:21.931" starttime="20191221 14:47:21.313"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:21.931" critical="yes" starttime="20191221 14:47:21.310">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625990&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s2-t2" name="TestPost200ID">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:21.934" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:21.935" starttime="20191221 14:47:21.933"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:21.937" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:21.937" starttime="20191221 14:47:21.936"></status>
</kw>
<kw name="Create List" library="BuiltIn">
<doc>Returns a list containing given items.</doc>
<arguments>
<arg>a2</arg>
<arg>test</arg>
</arguments>
<assign>
<var>${list}</var>
</assign>
<msg timestamp="20191221 14:47:21.938" level="INFO">${list} = [u'a2', u'test']</msg>
<status status="PASS" endtime="20191221 14:47:21.938" starttime="20191221 14:47:21.938"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone2</arg>
<arg>author=Jake Peralta</arg>
<arg>content=some content</arg>
<arg>tags=${list}</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:21.939" level="INFO">${params} = {u'title': u'Emma Stone2', u'author': u'Jake Peralta', u'content': u'some content', u'tags': [u'a2', u'test']}</msg>
<status status="PASS" endtime="20191221 14:47:21.939" starttime="20191221 14:47:21.938"></status>
</kw>
<kw name="Put Request" library="RequestsLibrary">
<doc>Send a PUT request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:21.941" level="INFO">PUT Request using : uri=/api/v1/post, files=None, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"title": "Emma Stone2", "author": "Jake Peralta", "content": "some content", "tags": ["a2", "test"]} 
json=None</msg>
<msg timestamp="20191221 14:47:21.944" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.146" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.552" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046319d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.558" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625c10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:22.559" starttime="20191221 14:47:21.940"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:22.559" critical="yes" starttime="20191221 14:47:21.932">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625c10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s2-t3" name="TestPost404Title">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:22.563" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:22.563" starttime="20191221 14:47:22.562"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:22.564" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:22.565" starttime="20191221 14:47:22.564"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone3</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:22.565" level="INFO">${params} = {u'title': u'Emma Stone3'}</msg>
<status status="PASS" endtime="20191221 14:47:22.565" starttime="20191221 14:47:22.565"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>json=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:22.566" level="INFO">GET Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data=None 
json={u'title': u'Emma Stone3'}</msg>
<msg timestamp="20191221 14:47:22.571" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.776" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631790&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.185" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631250&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.189" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631ad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:23.190" starttime="20191221 14:47:22.566"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:23.190" critical="yes" starttime="20191221 14:47:22.561">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631ad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s2-t4" name="TestPost404ID">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:23.192" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:23.194" starttime="20191221 14:47:23.192"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:23.196" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:23.196" starttime="20191221 14:47:23.194"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>_id=000000000000000000000000</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:23.197" level="INFO">${params} = {u'_id': u'000000000000000000000000'}</msg>
<status status="PASS" endtime="20191221 14:47:23.197" starttime="20191221 14:47:23.196"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>json=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:23.198" level="INFO">GET Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data=None 
json={u'_id': u'000000000000000000000000'}</msg>
<msg timestamp="20191221 14:47:23.202" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.404" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.812" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f8d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.816" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463fa50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:23.816" starttime="20191221 14:47:23.197"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:23.816" critical="yes" starttime="20191221 14:47:23.191">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463fa50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s2-t5" name="TestPost400">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:23.820" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:23.821" starttime="20191221 14:47:23.819"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:23.822" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:23.822" starttime="20191221 14:47:23.821"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>i=csc301a2</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:23.822" level="INFO">${params} = {u'i': u'csc301a2'}</msg>
<status status="PASS" endtime="20191221 14:47:23.822" starttime="20191221 14:47:23.822"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>json=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:23.824" level="INFO">GET Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data=None 
json={u'i': u'csc301a2'}</msg>
<msg timestamp="20191221 14:47:23.827" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.033" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046025d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.441" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631390&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.445" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631090&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:24.445" starttime="20191221 14:47:23.823"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:24.445" critical="yes" starttime="20191221 14:47:23.817">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631090&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" endtime="20191221 14:47:24.447" starttime="20191221 14:47:21.305"></status>
</suite>
<suite source="/Users/vinoshantharmalenkam/Desktop/CSCC01-Fall-2019/a2/rootFolder/testCases/Test3-405.robot" id="s1-s3" name="Test3-405">
<test id="s1-s3-t1" name="TestPost405">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:24.456" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:24.456" starttime="20191221 14:47:24.455"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:24.457" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:24.457" starttime="20191221 14:47:24.456"></status>
</kw>
<kw name="Create List" library="BuiltIn">
<doc>Returns a list containing given items.</doc>
<arguments>
<arg>a2</arg>
<arg>test</arg>
</arguments>
<assign>
<var>${list}</var>
</assign>
<msg timestamp="20191221 14:47:24.457" level="INFO">${list} = [u'a2', u'test']</msg>
<status status="PASS" endtime="20191221 14:47:24.458" starttime="20191221 14:47:24.457"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone</arg>
<arg>content=some content</arg>
<arg>tags=${list}</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:24.458" level="INFO">${params} = {u'title': u'Emma Stone', u'content': u'some content', u'tags': [u'a2', u'test']}</msg>
<status status="PASS" endtime="20191221 14:47:24.458" starttime="20191221 14:47:24.458"></status>
</kw>
<kw name="Post Request" library="RequestsLibrary">
<doc>Send a POST request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:24.459" level="INFO">POST Request using : uri=/api/v1/post, files=None, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"title": "Emma Stone", "content": "some content", "tags": ["a2", "test"]} 
json=None</msg>
<msg timestamp="20191221 14:47:24.462" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104655610&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.665" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046557d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.070" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104655990&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.074" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463d710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:25.074" starttime="20191221 14:47:24.458"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:25.075" critical="yes" starttime="20191221 14:47:24.454">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463d710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" endtime="20191221 14:47:25.076" starttime="20191221 14:47:24.451"></status>
</suite>
<suite source="/Users/vinoshantharmalenkam/Desktop/CSCC01-Fall-2019/a2/rootFolder/testCases/Test4DELETE.robot" id="s1-s4" name="Test4DELETE">
<test id="s1-s4-t1" name="TestPost200ID">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:25.083" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:25.084" starttime="20191221 14:47:25.083"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:25.085" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:25.085" starttime="20191221 14:47:25.084"></status>
</kw>
<kw name="Create List" library="BuiltIn">
<doc>Returns a list containing given items.</doc>
<arguments>
<arg>a2</arg>
<arg>test</arg>
</arguments>
<assign>
<var>${list}</var>
</assign>
<msg timestamp="20191221 14:47:25.085" level="INFO">${list} = [u'a2', u'test']</msg>
<status status="PASS" endtime="20191221 14:47:25.085" starttime="20191221 14:47:25.085"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>title=Emma Stone2</arg>
<arg>author=Jake Peralta</arg>
<arg>content=some content</arg>
<arg>tags=${list}</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:25.086" level="INFO">${params} = {u'title': u'Emma Stone2', u'author': u'Jake Peralta', u'content': u'some content', u'tags': [u'a2', u'test']}</msg>
<status status="PASS" endtime="20191221 14:47:25.086" starttime="20191221 14:47:25.086"></status>
</kw>
<kw name="Put Request" library="RequestsLibrary">
<doc>Send a PUT request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:25.087" level="INFO">PUT Request using : uri=/api/v1/post, files=None, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"title": "Emma Stone2", "author": "Jake Peralta", "content": "some content", "tags": ["a2", "test"]} 
json=None</msg>
<msg timestamp="20191221 14:47:25.090" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.297" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a9d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.700" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ab90&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.704" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ad10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:25.704" starttime="20191221 14:47:25.086"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:25.705" critical="yes" starttime="20191221 14:47:25.082">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ad10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s4-t2" name="TestPost404ID">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:25.708" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:25.709" starttime="20191221 14:47:25.708"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:25.710" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:25.710" starttime="20191221 14:47:25.710"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>_id=000000000000000000000000</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:25.711" level="INFO">${params} = {u'_id': u'000000000000000000000000'}</msg>
<status status="PASS" endtime="20191221 14:47:25.711" starttime="20191221 14:47:25.711"></status>
</kw>
<kw name="Delete Request" library="RequestsLibrary">
<doc>Send a DELETE request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:25.713" level="INFO">DELETE Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"_id": "000000000000000000000000"} 
json=None</msg>
<msg timestamp="20191221 14:47:25.717" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.920" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a290&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.328" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a9d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.332" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ac10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:26.332" starttime="20191221 14:47:25.712"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:26.332" critical="yes" starttime="20191221 14:47:25.706">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ac10&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<test id="s1-s4-t3" name="TestPost400">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>localhost</arg>
<arg>http://localhost:8080</arg>
</arguments>
<msg timestamp="20191221 14:47:26.335" level="INFO">Creating Session using : alias=localhost, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" endtime="20191221 14:47:26.335" starttime="20191221 14:47:26.334"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<assign>
<var>${headers}</var>
</assign>
<msg timestamp="20191221 14:47:26.337" level="INFO">${headers} = {u'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20191221 14:47:26.337" starttime="20191221 14:47:26.336"></status>
</kw>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>i=csc301a2</arg>
</arguments>
<assign>
<var>${params}</var>
</assign>
<msg timestamp="20191221 14:47:26.338" level="INFO">${params} = {u'i': u'csc301a2'}</msg>
<status status="PASS" endtime="20191221 14:47:26.338" starttime="20191221 14:47:26.337"></status>
</kw>
<kw name="Delete Request" library="RequestsLibrary">
<doc>Send a DELETE request on the session object found using the
given `alias`</doc>
<arguments>
<arg>localhost</arg>
<arg>/api/v1/post</arg>
<arg>data=${params}</arg>
<arg>headers=${headers}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20191221 14:47:26.339" level="INFO">DELETE Request using : uri=/api/v1/post, params=None, timeout=None, allow_redirects=True
headers={'Connection': 'keep-alive', u'Content-Type': u'application/json', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.22.0'} 
data={"i": "csc301a2"} 
json=None</msg>
<msg timestamp="20191221 14:47:26.343" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666550&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.548" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.951" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046668d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.957" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666a50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" endtime="20191221 14:47:26.957" starttime="20191221 14:47:26.338"></status>
</kw>
<timeout value="5 seconds"></timeout>
<status status="FAIL" endtime="20191221 14:47:26.959" critical="yes" starttime="20191221 14:47:26.333">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/post (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666a50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" endtime="20191221 14:47:26.961" starttime="20191221 14:47:25.078"></status>
</suite>
<status status="FAIL" endtime="20191221 14:47:26.964" starttime="20191221 14:47:19.906"></status>
</suite>
<statistics>
<total>
<stat fail="11" pass="0">Critical Tests</stat>
<stat fail="11" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="11" id="s1" name="testCases" pass="0">testCases</stat>
<stat fail="2" id="s1-s1" name="Test1PUT" pass="0">testCases.Test1PUT</stat>
<stat fail="5" id="s1-s2" name="Test2GET" pass="0">testCases.Test2GET</stat>
<stat fail="1" id="s1-s3" name="Test3-405" pass="0">testCases.Test3-405</stat>
<stat fail="3" id="s1-s4" name="Test4DELETE" pass="0">testCases.Test4DELETE</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20191221 14:47:20.061" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10458af50&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.264" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459e790&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.668" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10459e3d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.685" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046144d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:20.891" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104614690&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.296" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104614850&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.316" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625490&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.518" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.926" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104625810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:21.944" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.146" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.552" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046319d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.571" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631650&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:22.776" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631790&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.185" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631250&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.202" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f550&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.404" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.812" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f8d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:23.827" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10463f710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.033" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046025d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.441" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104631390&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.462" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104655610&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:24.665" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046557d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.070" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104655990&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.090" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a810&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.297" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a9d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.700" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465ab90&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.717" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a5d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:25.920" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a290&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.328" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10465a9d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.343" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666550&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.548" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x104666710&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
<msg timestamp="20191221 14:47:26.951" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1046668d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /api/v1/post</msg>
</errors>
</robot>
